spring.application.name=MusicUbam
server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/musica?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=admin
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.open-in-view=false
debug=false
logging.level.root=info
logging.level.org.springframework=info
logging.level.org.hibernate.SQL=warn

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=2048MB
spring.servlet.multipart.max-request-size=2048MB

spring.mail.host=smtp.hostinger.com
spring.mail.port=465
spring.mail.protocol=smtps
spring.mail.username=admin@chat.portafolioestudiantil.com
spring.mail.password=lHDa8ZdC+o4
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.hostinger.com
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000
spring.mail.properties.mail.smtps.auth=true
spring.mail.properties.mail.smtps.ssl.enable=true
spring.mail.properties.mail.smtps.ssl.trust=smtp.hostinger.com
spring.mail.properties.mail.smtps.connectiontimeout=10000
spring.mail.properties.mail.smtps.timeout=10000
spring.mail.properties.mail.smtps.writetimeout=10000

musicubam.mail.from=admin@chat.portafolioestudiantil.com
